USE [master]
GO
/****** Object:  Database [API_Proyecto3.Data]    Script Date: 27/11/2023 14:22:59 ******/
CREATE DATABASE [API_Proyecto3.Data]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'API_Proyecto3.Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\API_Proyecto3.Data.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'API_Proyecto3.Data_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\API_Proyecto3.Data_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [API_Proyecto3.Data] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [API_Proyecto3.Data].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [API_Proyecto3.Data] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET ARITHABORT OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [API_Proyecto3.Data] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [API_Proyecto3.Data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [API_Proyecto3.Data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET  ENABLE_BROKER 
GO
ALTER DATABASE [API_Proyecto3.Data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [API_Proyecto3.Data] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [API_Proyecto3.Data] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [API_Proyecto3.Data] SET  MULTI_USER 
GO
ALTER DATABASE [API_Proyecto3.Data] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [API_Proyecto3.Data] SET DB_CHAINING OFF 
GO
ALTER DATABASE [API_Proyecto3.Data] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [API_Proyecto3.Data] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [API_Proyecto3.Data] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [API_Proyecto3.Data] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [API_Proyecto3.Data] SET QUERY_STORE = OFF
GO
USE [API_Proyecto3.Data]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 27/11/2023 14:22:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empleado]    Script Date: 27/11/2023 14:22:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado](
	[EmpleadoId] [int] IDENTITY(1,1) NOT NULL,
	[Ingreso] [datetime2](7) NOT NULL,
	[Nombre] [nvarchar](max) NOT NULL,
	[Apellidos] [nvarchar](max) NOT NULL,
	[FechaNacimiento] [datetime2](7) NULL,
	[NumCedula] [nvarchar](max) NULL,
	[Direccion] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NULL,
	[Telefono] [nvarchar](max) NULL,
	[PersonaContacto] [nvarchar](max) NULL,
	[ParqueoId] [int] NOT NULL,
 CONSTRAINT [PK_Empleado] PRIMARY KEY CLUSTERED 
(
	[EmpleadoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Parqueo]    Script Date: 27/11/2023 14:22:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Parqueo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](max) NOT NULL,
	[MaxVehiculos] [int] NOT NULL,
	[HoraApertura] [datetime2](7) NOT NULL,
	[HoraCierre] [datetime2](7) NOT NULL,
	[TotalVendido] [int] NOT NULL,
	[TarifaHora] [int] NOT NULL,
	[TarifaMediaHora] [int] NOT NULL,
 CONSTRAINT [PK_Parqueo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tiquete]    Script Date: 27/11/2023 14:22:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tiquete](
	[TiqueteId] [int] IDENTITY(1,1) NOT NULL,
	[Ingreso] [datetime2](7) NOT NULL,
	[Salida] [datetime2](7) NULL,
	[Placa] [nvarchar](max) NOT NULL,
	[EnUso] [bit] NOT NULL,
	[Monto_Pagado] [int] NULL,
	[ParqueoId] [int] NOT NULL,
	[TarifaHora] [int] NULL,
	[TarifaMediaHora] [int] NULL,
 CONSTRAINT [PK_Tiquete] PRIMARY KEY CLUSTERED 
(
	[TiqueteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Empleado_ParqueoId]    Script Date: 27/11/2023 14:22:59 ******/
CREATE NONCLUSTERED INDEX [IX_Empleado_ParqueoId] ON [dbo].[Empleado]
(
	[ParqueoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Tiquete_ParqueoId]    Script Date: 27/11/2023 14:22:59 ******/
CREATE NONCLUSTERED INDEX [IX_Tiquete_ParqueoId] ON [dbo].[Tiquete]
(
	[ParqueoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Parqueo] ADD  DEFAULT ((0)) FOR [TarifaHora]
GO
ALTER TABLE [dbo].[Parqueo] ADD  DEFAULT ((0)) FOR [TarifaMediaHora]
GO
ALTER TABLE [dbo].[Empleado]  WITH CHECK ADD  CONSTRAINT [FK_Empleado_Parqueo_ParqueoId] FOREIGN KEY([ParqueoId])
REFERENCES [dbo].[Parqueo] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Empleado] CHECK CONSTRAINT [FK_Empleado_Parqueo_ParqueoId]
GO
ALTER TABLE [dbo].[Tiquete]  WITH CHECK ADD  CONSTRAINT [FK_Tiquete_Parqueo_ParqueoId] FOREIGN KEY([ParqueoId])
REFERENCES [dbo].[Parqueo] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Tiquete] CHECK CONSTRAINT [FK_Tiquete_Parqueo_ParqueoId]
GO
USE [master]
GO
ALTER DATABASE [API_Proyecto3.Data] SET  READ_WRITE 
GO
